config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  root 'todo_lists#index'
  
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
  
  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates :content, presence: true, length: { minimum: 3 }

  scope :complete, -> { where.not(completed_at: nil) }
  scope :incomplete, -> { where(completed_at: nil) }

  def completed?
    !completed_at.blank?
  end

  def toggle_completion!
    if completed?
      update_attribute(:completed_at, nil)
    else
      update_attribute(:completed_at, Time.now)
    end
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :require_user
  before_action :find_todo_list
  before_action :find_todo_item, except: [ :index, :new, :create ]

  def index; end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding the todo list item."
      render action: :new
    end
  end

  def edit; end

  def update
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "The todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "The todo item was deleted."
    else
      flash[:error] = "The todo item could not be deleted."
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item.toggle_completion!
    redirect_to todo_list_todo_items_path, notice: "Todo item updated."
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private
  def find_todo_list
    @todo_list = current_user.todo_lists.find(params[:todo_list_id])
  end

  def find_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

		<ul>
			<% @todo_item.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit "Save" %>

app/views/todo_items/_todo_item.html.erb
<li id="<%= dom_id(todo_item) %>" class="todo_item row">
	<div class="small-2 medium-1 columns checkmark">
		<% if todo_item.completed? %>
			<%= link_to "Mark Incomplete", complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch, class: "icon-check checked hide-text" %>
		<% else %>
			<%= link_to "Mark Incomplete", complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch, class: "icon-check checked hide-text" %>
		<% end %>
		
	</div>
	<div class="small-10 medium-11 columns truncate todo_content" title="<%= todo_item.content%>">
		<%= link_to todo_item.content, edit_todo_list_todo_item_path(@todo_list, todo_item) %>
	</div>
</li>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
	<%= render partial: form%>
<% end %>

app/views/todo_items/index.html.erb
<h2 class="page-title truncate" title="<%= @todo_list.title %>"><%= @todo_list.title %></h2>

<ul class="list todo_items no-bullet">
	<%= render @todo_list.todo_items %>
</ul>

<%= link_to "New Todo Item", new_todo_list_todo_item_path %>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Add Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>