config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  root 'todo_lists#index'
  
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
  
  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items

  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  
  def has_completed_items?
    todo_items.complete.size > 0
  end

  def has_incomplete_items?
    todo_items.incomplete.size > 0
  end
  
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_user
  before_action :find_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = current_user.todo_lists
  end

  def show; end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def edit; end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
      <ul>
				<% @todo_list.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
      </ul>
    </div>
  <% end %>

  <fieldgroup>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </fieldgroup>
  <%= f.submit %>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<li id="<%= dom_id(todo_list) %>" class="clearfix">
	<%= link_to todo_list_todo_items_path(todo_list), class: "row" do %>
		<div class="small-10 medium-11 columns truncate" title="<%= todo_list.title %>">
			<%= todo_list.title %>
		</div>
		<div class="small-2 medium-1 columns">
			<label class="label round">
				<%= todo_list.todo_items.size %>
			</label>
		</div>
	<% end %>
</li>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h2 class="page-title truncate">Listing Todo Lists</h2>

<ul class="todo_lists no-bullet">
	<%= render @todo_lists %>
</ul>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h1><%= @todo_list.title %></h1>

<% if @todo_list.has_incomplete_items? %>
	<h3>Incomplete</h3>
	<ul>
		<% @todo_list.todo_items.incomplete.each do |todo_item| %>
			<li><%= todo_item.content %></li>
		<% end %>
	</ul>
<% end %>

<% if @todo_list.has_completed_items? %>
	<h3>Complete</h3>
	<ul>
		<% @todo_list.todo_items.complete.each do |todo_item| %>
			<li><%= todo_item.content %></li>
		<% end %>
	</ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>