config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  root 'todo_lists#index'
  
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
  
  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="row">
	<nav class="small-12 small-centered medium-8 medium-centred large-5 large-centered columns">
		<% if logged_in? %>
			<%= link_to "Settings", edit_user_path(current_user)  %>
		<% end %>
	</nav>
</footer>

app/views/layouts/_navigation.html.erb
<header class="row global-header">
	<nav class="small-12 small-centered medium-8 medium-centred large-5 large-centered columns">
		<%= link_to "TODO Lists", todo_lists_path %></li>
		<% if logged_in? %>
			<%= link_to "Log Out", logout_path, method: :delete %></li>
		<% else %>
			<%= link_to "Log In", new_user_session_path %>
			<%= link_to "Sign Up", new_user_path %>
		<% end %>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag "vendor/modernizer" %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<% flash.each do |type, message| %>
		<output class="flash alert-box text-center <%= type %>">
			<%= message %>
			<a href="#" class="close">&times;</a>
		</output>
	<% end %>

	<section class="row collapse">
		<main class="small-12 small-centered medium-8 medium-centred large-5 large-centered columns">
			<%= yield %>
		</main>
	</section>

	<%= render 'layouts/footer' %>
</body>
</html>